### ISSUE TITLE
Don't want to pester... but does this need to be updated?

### ISSUE THREAD

**Issue by x99percent** [robertsLando/Zwave2Mqtt-docker#3]
Daniel, I can see that the OpenZWave/Zwave2Mqtt project is getting frequent updates. Does this docker container automatically pull/use the latest code, or does this project need an update?

Would really like to test out the latest version of this app, but everything I'm using is dockerized. Ideally, I'd like to be able to pull the latest version from hub.docker.com

Thanks in advance!

**Comment by robertsLando** [comment]
Hi,

I didn’t updated the docker image to latest version because after openzwave 1.6 release 
there was lot changes and I was waiting to have some important features fixed on underlying library node-openzwave-shared like the options changed and many others, once it will be ready I will immediately update the version. 

Anyway, if I found some time in this days or next week I update to latest version as I understand lot peoples are using it and pretend to use latest version. 

Daniel

**Comment by x99percent** [comment]
Thank you, Daniel!

**Comment by robertsLando** [comment]
@x99percent Hi, I'm building latest version now :)
