### ISSUE TITLE
Set timezone in container

### ISSUE THREAD

**Issue by flic** [robertsLando/Zwave2Mqtt-docker#4]
Hi.

I'd love to be able to set the correct timezone in the container so that log messages and timestamps are correct. I tried -e TZ=Europe/Stockholm, but it didn't seem to do the trick.

Is it possible to configure the timezone in some way?

Thanks

**Comment by robertsLando** [comment]
The -e option is ok but it doesn’t works because the container is an alpine container so it needs to install tzdata with apk (RUN apk add tzdata). Could you try to use the base makefile and add tzdata to apk deps and tell me if it works by using the -e option ? If so I will add tzdata to the base image

Daniel

**Comment by robertsLando** [comment]
Add “tzdata /“ under this line https://github.com/robertsLando/Zwave2Mqtt-docker/blob/master/Dockerfile#L76

**Comment by flic** [comment]
I'll try that and get back to you

**Comment by flic** [comment]
Yes, that worked perfectly
